
- name: variables from PLAY level
  hosts: localhost 
  vars:
    Course: "DevOps"
    Trainer: "Siva"
    Duration: "45MINS"
  tasks:
  - name: check variables
    vars: #task level
      Course: "AWS"
    ansible.builtin.debug:
      msg: "Hi, learning {{Course}},Tranier is {{Trainer}} hours is {{Duration}} " 